import { randomUUID } from "node:crypto";
import { getClassForGuid, getGuid, getInheritedClassDecoratorMap, type ClassDecoratorMap } from "../decorator-registry";
import { EntityDecorators, getModelGuidByEmid, PropertyValidationError, type DehydrateOptions, type EntityValidatorFn, type IdExtractorFn, type ModelDefinition, type ObservableEntity, type PropertyMetadata, type PropertyObserverFn, type StandardEntity, standardPropertyValidation } from "./decorators-types-core";

export const passthruDecode = (value: any) => value;
export const passthruEncode = (value: any) => value;

/**
 * Provides automated data normalization against user-supplied data from a `@Model` definition:
 * 
 * - user.data is prepared against modelDef:
 *   - process each key-value:
 *     - if mode=='create': # override user
 *       - if isAutoGenerated, use autoCreatedValue() or undefined
 *     - if mode=='update': # override user
 *       - if isReadOnly: remove key
 *       - else if isAutoUpdated: set with autoUpdatedValue() or remove key
 *   - inject system key-value overrides
 * - hydrate prepared data
 * - validate prepared data
 */
export const prepareDataForMutation = (modelDef: ModelDefinition, mode: 'create' | 'update', data: any, options?: { injectData?: Record<string, any>; removeKeys?: string[] }) => {
    const result: ReturnType<ModelDefinition['prepareData']> = {
        data: {},
        removed: {},
    }

    const { injectData = {}, removeKeys = [] } = (options ?? {});
    const isCreate = mode === 'create';
    const isUpdate = !isCreate;

    for (const [propertyKey, meta] of Object.entries(modelDef.properties)) {
        const isReadOnly = meta.isReadOnly || meta.isAutoCreated || meta.isAutoUpdated;
        if (meta.isAutoCreated) {
            // case: always remove; only auto-add back on-create
            result.removed[propertyKey] = data[propertyKey];
            if (isCreate && meta.autoCreatedValue) {
                result.data[propertyKey] = meta.autoCreatedValue(propertyKey, modelDef);
            }
        } else if (meta.isAutoUpdated) {
            // case: always remove; only auto-add back on-update
            result.removed[propertyKey] = data[propertyKey];
            if (isUpdate && meta.autoUpdatedValue) {
                result.data[propertyKey] = meta.autoUpdatedValue(propertyKey, modelDef);
            }
        } else if (isUpdate && isReadOnly) {
            // case: always remove on-update
            result.removed[propertyKey] = data[propertyKey];
        } else {
            result.data[propertyKey] = data[propertyKey];
        }
    }

    // inject system key-value overrides
    result.data = { ...result.data, ...injectData };
    for (const key of removeKeys) {
        if (result.data[key] === undefined) continue;
        result.removed[key] = result.data[key];
        delete result.data[key];
    }

    return result;
}

// export const standardPropertyValidation = (value: any, propertyName: string, modelDef: ModelDefinition) => 
//     quickPropertyValidation(value, propertyName, modelDef.properties[propertyName], modelDef.getEmid());

const __uuid_keys: Record<string, boolean> = { _id: true, id: true };

export const PROP_REL_ENCODING = '_rel_encType';
export const PROP_REL_EMID = '_rel_emid';
export const UUID_DEFAULT_PREFIX = '*';
export const VALUE_UNDEFINED_PREFIX = '*undefined:';

const defaultIdExtractor: IdExtractorFn = (entity, keys) => {
    const extractedKeys: Record<string, any> = {};
    for (const key of keys) {
        if (entity[key] !== undefined)
            extractedKeys[key] = entity[key];
        else if (__uuid_keys[key])
            extractedKeys[key] = `${UUID_DEFAULT_PREFIX}${randomUUID()}`
        else
            extractedKeys[key] = `${VALUE_UNDEFINED_PREFIX}${key}`;
    }
    return extractedKeys;
}

export const dehydrateProperty = (value: any, propDef: PropertyMetadata, entity: any, { idExtractor = defaultIdExtractor }: DehydrateOptions = {}) => {
    let normValue = value;
    if (propDef.relationship) {
        const { emid: emidDefault, relType, emidConstraints: modelConstraints } = propDef.relationship;
        if (relType === 'embedded')
            return normValue;

        const {preservedProps: keys} = propDef.relationship;
        // @todo handle isArray
        const relEntity = value;
        if (typeof relEntity !== 'object')
            return null;

        // project keys + encType & emid/default
        const extractedKeys = idExtractor(relEntity, keys, propDef);
        const emid = relEntity[PROP_REL_EMID] ?? emidDefault;
        // @todo apply emidConstraints

        normValue = {
            ...extractedKeys,
            [PROP_REL_ENCODING]: relType,
            [PROP_REL_EMID]: emid,
            // @todo _rel_parent_id
        };
    }

    return normValue;
}

export class Dehydrator { }

/**
 * Produces 1+ documents containing:
 * 
 * - the root entity being dehydrated
 * - any property defined as `relationship=child` (recurse)
 */
export const dehydrateEntityWithRelations = ({entity, modelDef, options}: {entity: any, modelDef: ModelDefinition, options?: DehydrateOptions}) => {
    const docs: Record<string, any>[] = [];

    const { depth: maxDepth = -1 } = (options ?? {});

    const recurseDehydrate = (ent: any, modelDef?: ModelDefinition, { depth = 0 }: DehydrateOptions = {}) => {
        if (!modelDef || (maxDepth >= 0 && depth >= maxDepth))
            return;

        const { id, _id, [PROP_REL_EMID]: emid, ...rest } = ent;
        const doc: Record<string, any> = { id, _id, [PROP_REL_EMID]: emid };
        docs.push(doc);

        for (const [propName, propDef] of Object.entries(modelDef.properties)) {
            const value = dehydrateProperty(ent[propName], propDef, ent, options);
            doc[propName] = value;
            if (propDef.relationship?.relType === 'child') {
                recurseDehydrate(
                    value,
                    getModelDefinitionByEmid(value[PROP_REL_EMID]),
                    { depth: depth + 1 }
                );
            }
        }
    }

    recurseDehydrate(entity, modelDef);
    return docs;
}

export const hydrateEntityWithRelations = ({ entity: _entity, modelDef, data }: {
    entity?: any;
    modelDef?: ModelDefinition;
    data: Record<string, any>;
}) => {
    if (!modelDef) return undefined;
    const entity = _entity ?? (modelDef.createInstance());

    Object.entries(modelDef.properties).forEach(([propName, propDef]) => {
        if (data[propName] === undefined) return;

        const value = data[propName];
        if (propDef.relationship) {
            const { relType, emid: emidDefault } = propDef.relationship;
            if (value instanceof Array) {
                entity[propName] = value.map(subent => hydrateEntityWithRelations({
                    modelDef: getModelDefinitionByEmid(subent[PROP_REL_EMID] ?? emidDefault),
                    data: subent,
                }) ?? subent);
            } else {
                entity[propName] = hydrateEntityWithRelations({
                    modelDef: getModelDefinitionByEmid(value[PROP_REL_EMID]),
                    data: value,
                }) ?? value;
            }
            
            if (relType !== 'embedded') {
                // @todo fetch deep entities
                console.warn(`🟠 hydrateEntityWithRelations: data fetching not-supported: ${relType}`, { relType }, value);
            }
        } else {
            entity[propName] = propDef.decode(value, propName, modelDef);
        }
    })

    return entity;
}

export const makeObservableEntity = <Entity extends object>(modelDef: ModelDefinition, entity: Entity): Entity & ObservableEntity => {
    const observers: Record<string, PropertyObserverFn[]> = {};

    const notifyObservers = (key: string, value: any) => {
        [ ...(observers[key as string] ?? []), ...(observers['*'] ?? []) ].forEach(
            (observer, idx) => {
                try {
                    observer(key as string, value)
                } catch (error) {
                    console.error('🟠 observableEntity.error.observer', { error, observer, observerIndex: idx, key, value });
                }
            }
        );
    }

    const proxy = new Proxy(entity, {
        set: (target, prop, value) => {
            const key = prop as string;
            target[key as keyof typeof target] = value;

            if (modelDef.properties[key]) {
                notifyObservers(key, value);
            }

            return true;
        }
    }) as typeof entity & ObservableEntity;

    proxy.$observeWith = (observer, onProperties) => {
        const keys = (onProperties === '*' || onProperties === undefined) ? ['*'] : (Array.isArray(onProperties) ? onProperties : [onProperties]);
        for (const key of keys) {
            if (!observers[key]) observers[key] = [];
            observers[key].push(observer);
        }

        return () => {
            for (const key of keys) {
                observers[key] = observers[key].filter(o => o !== observer);
            }
        };
    }

    return proxy;
}

const modelDefCache: Record<string, ModelDefinition> = {};

/**
 * Creates a ModelDefinition instance from a ClassDecoratorMap. The modelDef operates on
 * concrete objects and does not bind in any way to the instance/class definition.
 */
export const makeModelDefinition = (allDecs: ClassDecoratorMap): ModelDefinition => {
    const modelMeta = allDecs.class[EntityDecorators.Model];
    const emid = `${modelMeta.collection}@${modelMeta.name}`;
    const propsForDecorator = allDecs.properties[EntityDecorators.Property] ?? {};
    const guid = allDecs.guid;

    const properties = Object.entries(propsForDecorator).reduce((acc, [property, metadata]) => {
        const { decode = passthruDecode, encode = passthruEncode, validate: validateFn = () => undefined, ...rest } = metadata;
        acc[property] = {
            name: metadata.name ?? property,
            decode,
            encode,
            validate: (value: any, propDefName) => 
                standardPropertyValidation(value, propDefName, metadata as PropertyMetadata, emid),
            ...rest
        };
        return acc;
    }, {} as ModelDefinition['properties']);

    const hydrateEntity = (data: Record<string, any>, entity?: any) => {
        return hydrateEntityWithRelations({
            modelDef,
            data,
            entity,
        });
    }

    const dehydrateEntity = (entity: any, options?: DehydrateOptions) => {
        const data = dehydrateEntityWithRelations({entity, modelDef, options});
        // for now, easiest way to remove undefined values
        return data ? JSON.parse(JSON.stringify(data)) : data;
    }

    const removeReadOnly = (data: Record<string, any>) => {
        const ndata = { ...data };
        for (const property in properties) {
            const def = properties[property];
            if (def.isReadOnly || def.isAutoCreated || def.isAutoUpdated) {
                delete ndata[property];
            }
        }
        return ndata;
    }

    const prepareData: ModelDefinition['prepareData'] = (mode, data, options) => {
        return prepareDataForMutation(modelDef, mode, data, options ?? {});
    }

    const modelDef: ModelDefinition = {
        // cursor was complaining about name/collection not explicitly defined. why???
        name: modelMeta.name,
        collection: modelMeta.collection,
        ...modelMeta,
        properties,
        getEmid: () => emid,
        hydrateEntity,
        dehydrateEntity,
        removeReadOnly,
        prepareData,
        createInstance: () => new (getClassForGuid(guid))(),
    }

    return modelDef;
}

/**
 * Gets/creates a static ModelDefinition object from inherited @Model classes.
 * @param clazz 
 * @returns 
 */
export const getModelDefinition = (clazz: any) => {
    const guid = getGuid(clazz);
    const cacheKey = guid;

    if (modelDefCache[cacheKey]) return modelDefCache[cacheKey];

    const allDecs = getInheritedClassDecoratorMap(clazz, [EntityDecorators.Model, EntityDecorators.Property, EntityDecorators.Validator]);
    if (!allDecs) return;

    modelDefCache[cacheKey] = makeModelDefinition(allDecs);
    return modelDefCache[cacheKey];
}

export const getModelDefinitionByGuid = (guid: string) => {
    const clazz = getClassForGuid(guid);
    if (!clazz) return undefined;
    return getModelDefinition(clazz);
}

export const getModelDefinitionByEmid = (emid: string) =>
    getModelDefinitionByGuid(getModelGuidByEmid(emid));